"""one-to-one user-team

Revision ID: 42b4e2a97f68
Revises: 
Create Date: 2024-06-12 23:34:57.124678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b4e2a97f68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_matches_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_players_id', table_name='players')
    op.drop_table('players')
    op.drop_index('ix_matchstatistics_id', table_name='matchstatistics')
    op.drop_table('matchstatistics')
    op.drop_index('ix_teams_id', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_leagues_id', table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('rules', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leagues_id', 'leagues', ['id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('matches_played', sa.INTEGER(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_teams_id', 'teams', ['id'], unique=False)
    op.create_table('matchstatistics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goals_scored', sa.INTEGER(), nullable=True),
    sa.Column('shots', sa.INTEGER(), nullable=True),
    sa.Column('shots_on_target', sa.INTEGER(), nullable=True),
    sa.Column('possession', sa.INTEGER(), nullable=True),
    sa.Column('passes', sa.INTEGER(), nullable=True),
    sa.Column('pass_accuracy', sa.INTEGER(), nullable=True),
    sa.Column('fouls', sa.INTEGER(), nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), nullable=True),
    sa.Column('red_cards', sa.INTEGER(), nullable=True),
    sa.Column('offsides', sa.INTEGER(), nullable=True),
    sa.Column('corners', sa.INTEGER(), nullable=True),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matchstatistics_id', 'matchstatistics', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('sex', sa.VARCHAR(length=6), nullable=True),
    sa.Column('num_of_goals', sa.INTEGER(), nullable=True),
    sa.Column('num_of_assists', sa.INTEGER(), nullable=True),
    sa.Column('num_of_yellow_cards', sa.INTEGER(), nullable=True),
    sa.Column('num_of_red_cards', sa.INTEGER(), nullable=True),
    sa.Column('num_of_matches_played', sa.INTEGER(), nullable=True),
    sa.Column('minutes_played', sa.INTEGER(), nullable=True),
    sa.Column('team_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_players_id', 'players', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.Column('team_1_id', sa.INTEGER(), nullable=True),
    sa.Column('team_2_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['team_1_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_2_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_matches_id', 'matches', ['id'], unique=False)
    # ### end Alembic commands ###
